version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1.9--apache-node-browsers
    steps:
      - checkout
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --optimize-autoloader --classmap-authoritative
      - run: composer dump-autoload --optimize --classmap-authoritative
      - save_cache:
          paths:
            - vendor
          key: composer-v1-{{ checksum "composer.json" }}
      - run: phpunit
      