version: 2
jobs:
    build:
        docker:
            - image: circleci/php:7.2.5-apache-stretch-node
        steps:
            - checkout
            - run: echo 'Hello World'
            - run: sudo apt install -y libsqlite3-dev zlib1g-dev
            - run: sudo docker-php-ext-install zip
            - run: ls -l ${HOME}/project
            - run: sudo composer self-update
            - restore_cache:
                keys:
                    - composer-v1-{{ checksum "composer.json" }}
                    - composer-v1-
            - run: composer install -n --optimize-autoloader --classmap-authoritative
            - run: composer dump-autoload --optimize --classmap-authoritative
            - save_cache:
                paths:
                    - vendor
                key: composer-v1-{{ checksum "composer.json" }}
            - run: sudo ./bin/console d:d:c --env=test
            - run: sudo ./bin/console d:s:c --env=test
            - run: sudo ./bin/console d:f:l -n
            - run: sudo ./vendor/bin/phpunit -v
