var classes = [
    {
        "name": "App\\Action\\LoginAction",
        "interface": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [],
        "lcom": 1,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 12,
        "loc": 19,
        "lloc": 7,
        "mi": 218.14,
        "mIwoC": 171,
        "commentWeight": 47.14,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Annotation\\ClientAnnotation",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 8,
        "loc": 13,
        "lloc": 5,
        "mi": 217.87,
        "mIwoC": 171,
        "commentWeight": 46.87,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\CacheKernel",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\HttpCache\\HttpCache"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\HttpCache\\HttpCache"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\DataFixtures\\ClientFixtures",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "load",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture",
            "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface",
            "Doctrine\\Common\\Persistence\\ObjectManager",
            "App\\Entity\\Client",
            "DateTime",
            "App\\Entity\\Client",
            "DateTime",
            "App\\Entity\\Client",
            "DateTime",
            "App\\Entity\\Client",
            "DateTime",
            "App\\Entity\\Client",
            "DateTime"
        ],
        "parents": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture"
        ],
        "lcom": 1,
        "length": 105,
        "vocabulary": 30,
        "volume": 515.22,
        "difficulty": 1.62,
        "effort": 835.02,
        "level": 0.62,
        "bugs": 0.17,
        "time": 46,
        "intelligentContent": 317.9,
        "number_operators": 11,
        "number_operands": 94,
        "number_operators_unique": 1,
        "number_operands_unique": 29,
        "cloc": 9,
        "loc": 71,
        "lloc": 62,
        "mi": 67.98,
        "mIwoC": 41.78,
        "commentWeight": 26.2,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.11,
        "relativeSystemComplexity": 64.11,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 0.22,
        "totalSystemComplexity": 128.22,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\DataFixtures\\ProductFixtures",
        "interface": false,
        "methods": [
            {
                "name": "load",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture",
            "Doctrine\\Common\\Persistence\\ObjectManager",
            "App\\Entity\\Product",
            "App\\Entity\\Product",
            "App\\Entity\\Product",
            "App\\Entity\\Product",
            "App\\Entity\\Product"
        ],
        "parents": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture"
        ],
        "lcom": 1,
        "length": 121,
        "vocabulary": 51,
        "volume": 686.36,
        "difficulty": 1.16,
        "effort": 796.18,
        "level": 0.86,
        "bugs": 0.23,
        "time": 44,
        "intelligentContent": 591.69,
        "number_operators": 5,
        "number_operands": 116,
        "number_operators_unique": 1,
        "number_operands_unique": 50,
        "cloc": 6,
        "loc": 78,
        "lloc": 72,
        "mi": 60.32,
        "mIwoC": 39.49,
        "commentWeight": 20.83,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.08,
        "relativeSystemComplexity": 121.08,
        "totalStructuralComplexity": 121,
        "totalDataComplexity": 0.08,
        "totalSystemComplexity": 121.08,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\DataFixtures\\UserFixtures",
        "interface": false,
        "methods": [
            {
                "name": "load",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture",
            "Doctrine\\Common\\Persistence\\ObjectManager",
            "App\\Entity\\User",
            "DateTime",
            "App\\Entity\\User",
            "DateTime",
            "App\\Entity\\User",
            "DateTime",
            "App\\Entity\\User",
            "DateTime",
            "App\\Entity\\User",
            "DateTime"
        ],
        "parents": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture"
        ],
        "lcom": 1,
        "length": 192,
        "vocabulary": 27,
        "volume": 912.94,
        "difficulty": 12.35,
        "effort": 11272.8,
        "level": 0.08,
        "bugs": 0.3,
        "time": 626,
        "intelligentContent": 73.94,
        "number_operators": 50,
        "number_operands": 142,
        "number_operators_unique": 4,
        "number_operands_unique": 23,
        "cloc": 6,
        "loc": 69,
        "lloc": 63,
        "mi": 61.27,
        "mIwoC": 39.21,
        "commentWeight": 22.06,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.09,
        "relativeSystemComplexity": 100.09,
        "totalStructuralComplexity": 100,
        "totalDataComplexity": 0.09,
        "totalSystemComplexity": 100.09,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Doctrine\\CurrentClientExtension",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "applyToCollection",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "applyToItem",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addWhere",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\Extension\\QueryCollectionExtensionInterface",
            "ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\Extension\\QueryItemExtensionInterface",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorageInterface",
            "Symfony\\Component\\Security\\Core\\Authorization\\AuthorizationCheckerInterface",
            "Doctrine\\ORM\\QueryBuilder",
            "ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\Util\\QueryNameGeneratorInterface",
            "Doctrine\\ORM\\QueryBuilder",
            "ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\Util\\QueryNameGeneratorInterface",
            "Doctrine\\ORM\\QueryBuilder"
        ],
        "parents": [],
        "lcom": 1,
        "length": 47,
        "vocabulary": 19,
        "volume": 199.65,
        "difficulty": 5.2,
        "effort": 1038.19,
        "level": 0.19,
        "bugs": 0.07,
        "time": 58,
        "intelligentContent": 38.39,
        "number_operators": 8,
        "number_operands": 39,
        "number_operators_unique": 4,
        "number_operands_unique": 15,
        "cloc": 33,
        "loc": 61,
        "lloc": 28,
        "mi": 97.48,
        "mIwoC": 52.06,
        "commentWeight": 45.42,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.39,
        "relativeSystemComplexity": 64.39,
        "totalStructuralComplexity": 256,
        "totalDataComplexity": 1.56,
        "totalSystemComplexity": 257.56,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Entity\\Client",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUsername",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUsername",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRoles",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setRoles",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPassword",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPassword",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCreationDate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setCreationDate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removeUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSalt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "eraseCredentials",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "serialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "unserialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 17,
        "nbMethods": 12,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 12,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Entity\\Interfaces\\ClientInterface",
            "Symfony\\Component\\Security\\Core\\User\\UserInterface",
            "Serializable",
            "DateTime",
            "Doctrine\\Common\\Collections\\ArrayCollection",
            "DateTime",
            "DateTime",
            "ArrayAccess",
            "App\\Entity\\User",
            "App\\Entity\\User"
        ],
        "parents": [],
        "lcom": 3,
        "length": 55,
        "vocabulary": 10,
        "volume": 182.71,
        "difficulty": 4.75,
        "effort": 867.85,
        "level": 0.21,
        "bugs": 0.06,
        "time": 48,
        "intelligentContent": 38.46,
        "number_operators": 17,
        "number_operands": 38,
        "number_operators_unique": 2,
        "number_operands_unique": 8,
        "cloc": 76,
        "loc": 157,
        "lloc": 81,
        "mi": 86.44,
        "mIwoC": 42.4,
        "commentWeight": 44.05,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 3.14,
        "relativeSystemComplexity": 7.14,
        "totalStructuralComplexity": 68,
        "totalDataComplexity": 53.33,
        "totalSystemComplexity": 121.33,
        "pageRank": 0.17,
        "afferentCoupling": 3,
        "efferentCoupling": 7,
        "instability": 0.7,
        "violations": {}
    },
    {
        "name": "App\\Entity\\Product",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getBrand",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setBrand",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setName",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDescription",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setDescription",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPrice",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPrice",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWeight",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setWeight",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWidth",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setWidth",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHeight",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setHeight",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getScreen",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setScreen",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removeUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 21,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 8,
        "nbMethodsSetters": 8,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Entity\\Interfaces\\ProductInterface",
            "Doctrine\\Common\\Collections\\ArrayCollection",
            "ArrayAccess",
            "App\\Entity\\User",
            "App\\Entity\\User"
        ],
        "parents": [],
        "lcom": 1,
        "length": 64,
        "vocabulary": 12,
        "volume": 229.44,
        "difficulty": 4.4,
        "effort": 1009.53,
        "level": 0.23,
        "bugs": 0.08,
        "time": 56,
        "intelligentContent": 52.14,
        "number_operators": 20,
        "number_operands": 44,
        "number_operators_unique": 2,
        "number_operands_unique": 10,
        "cloc": 98,
        "loc": 198,
        "lloc": 100,
        "mi": 84.04,
        "mIwoC": 39.71,
        "commentWeight": 44.33,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 3.49,
        "relativeSystemComplexity": 7.49,
        "totalStructuralComplexity": 84,
        "totalDataComplexity": 73.33,
        "totalSystemComplexity": 157.33,
        "pageRank": 0.18,
        "afferentCoupling": 3,
        "efferentCoupling": 4,
        "instability": 0.57,
        "violations": {}
    },
    {
        "name": "App\\Entity\\User",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFirstName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setFirstName",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLastName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setLastName",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEmail",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setEmail",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMobileNumber",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setMobileNumber",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCreationDate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setCreationDate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getClient",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setClient",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 16,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 4,
        "nbMethodsSetters": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Entity\\Interfaces\\UserInterface",
            "DateTime",
            "DateTime",
            "DateTime",
            "App\\Entity\\Product",
            "App\\Entity\\Product",
            "App\\Entity\\Client",
            "App\\Entity\\Client"
        ],
        "parents": [],
        "lcom": 1,
        "length": 46,
        "vocabulary": 10,
        "volume": 152.81,
        "difficulty": 3.75,
        "effort": 573.03,
        "level": 0.27,
        "bugs": 0.05,
        "time": 32,
        "intelligentContent": 40.75,
        "number_operators": 16,
        "number_operands": 30,
        "number_operators_unique": 2,
        "number_operands_unique": 8,
        "cloc": 82,
        "loc": 158,
        "lloc": 76,
        "mi": 88.46,
        "mIwoC": 43.54,
        "commentWeight": 44.92,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 8.44,
        "relativeSystemComplexity": 8.44,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 135,
        "totalSystemComplexity": 135,
        "pageRank": 0.28,
        "afferentCoupling": 5,
        "efferentCoupling": 4,
        "instability": 0.44,
        "violations": {}
    },
    {
        "name": "App\\EventListener\\ClientFilterConfigurator",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onKernelRequest",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUser",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Doctrine\\ORM\\EntityManagerInterface",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorageInterface",
            "Doctrine\\Common\\Annotations\\Reader",
            "RuntimeException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 37,
        "vocabulary": 14,
        "volume": 140.87,
        "difficulty": 3.55,
        "effort": 499.46,
        "level": 0.28,
        "bugs": 0.05,
        "time": 28,
        "intelligentContent": 39.73,
        "number_operators": 11,
        "number_operands": 26,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 21,
        "loc": 51,
        "lloc": 30,
        "mi": 94.24,
        "mIwoC": 52.33,
        "commentWeight": 41.91,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.38,
        "relativeSystemComplexity": 49.38,
        "totalStructuralComplexity": 147,
        "totalDataComplexity": 1.13,
        "totalSystemComplexity": 148.13,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Filter\\ClientFilter",
        "interface": false,
        "methods": [
            {
                "name": "addFilterConstraint",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setAnnotationReader",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Doctrine\\ORM\\Query\\Filter\\SQLFilter",
            "Doctrine\\ORM\\Mapping\\ClassMetadata",
            "RuntimeException",
            "Doctrine\\Common\\Annotations\\Reader"
        ],
        "parents": [
            "Doctrine\\ORM\\Query\\Filter\\SQLFilter"
        ],
        "lcom": 1,
        "length": 41,
        "vocabulary": 18,
        "volume": 170.97,
        "difficulty": 6.5,
        "effort": 1111.29,
        "level": 0.15,
        "bugs": 0.06,
        "time": 62,
        "intelligentContent": 26.3,
        "number_operators": 15,
        "number_operands": 26,
        "number_operators_unique": 6,
        "number_operands_unique": 12,
        "cloc": 15,
        "loc": 44,
        "lloc": 29,
        "mi": 91.23,
        "mIwoC": 51.93,
        "commentWeight": 39.31,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.63,
        "relativeSystemComplexity": 10.63,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 3.25,
        "totalSystemComplexity": 21.25,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Filter\\CustomOrderFilter",
        "interface": false,
        "methods": [
            {
                "name": "extractProperties",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\Filter\\OrderFilter",
            "Symfony\\Component\\HttpFoundation\\Request"
        ],
        "parents": [
            "ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\Filter\\OrderFilter"
        ],
        "lcom": 1,
        "length": 4,
        "vocabulary": 3,
        "volume": 6.34,
        "difficulty": 0.75,
        "effort": 4.75,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 8.45,
        "number_operators": 1,
        "number_operands": 3,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 9,
        "loc": 17,
        "lloc": 8,
        "mi": 119.71,
        "mIwoC": 74.55,
        "commentWeight": 45.16,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Kernel",
        "interface": false,
        "methods": [
            {
                "name": "getCacheDir",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLogDir",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "registerBundles",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureContainer",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureRoutes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Component\\HttpKernel\\Kernel",
            "class",
            "Symfony\\Component\\DependencyInjection\\ContainerBuilder",
            "Symfony\\Component\\Config\\Loader\\LoaderInterface",
            "Symfony\\Component\\Config\\Resource\\FileResource",
            "Symfony\\Component\\Routing\\RouteCollectionBuilder"
        ],
        "parents": [
            "Symfony\\Component\\HttpKernel\\Kernel"
        ],
        "lcom": 1,
        "length": 102,
        "vocabulary": 31,
        "volume": 505.33,
        "difficulty": 6.63,
        "effort": 3352.66,
        "level": 0.15,
        "bugs": 0.17,
        "time": 186,
        "intelligentContent": 76.17,
        "number_operators": 33,
        "number_operands": 69,
        "number_operators_unique": 5,
        "number_operands_unique": 26,
        "cloc": 6,
        "loc": 43,
        "lloc": 39,
        "mi": 73.31,
        "mIwoC": 45.96,
        "commentWeight": 27.35,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.43,
        "relativeSystemComplexity": 25.43,
        "totalStructuralComplexity": 125,
        "totalDataComplexity": 2.17,
        "totalSystemComplexity": 127.17,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Repository\\ClientRepository",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository",
            "Doctrine\\Common\\Persistence\\ManagerRegistry",
            "parent"
        ],
        "parents": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository"
        ],
        "lcom": 1,
        "length": 2,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 8,
        "loc": 16,
        "lloc": 8,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Repository\\ProductRepository",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository",
            "Doctrine\\Common\\Persistence\\ManagerRegistry",
            "parent"
        ],
        "parents": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository"
        ],
        "lcom": 1,
        "length": 2,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 8,
        "loc": 16,
        "lloc": 8,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Repository\\UserRepository",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository",
            "Doctrine\\Common\\Persistence\\ManagerRegistry",
            "parent"
        ],
        "parents": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository"
        ],
        "lcom": 1,
        "length": 2,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 8,
        "loc": 16,
        "lloc": 8,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    }
]