App\Entity\Client:
    properties:
        username:
            - NotBlank: ~
        roles:
            - NotBlank: ~
        password:
            - notBlank: ~
        creationDate:
            - DateTime: ~

App\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: mobileNumber
            message: Numéro déjà alloué!
    properties:
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~
        email:
            - NotBlank: ~
        mobileNumber:
            - NotBlank: ~
        creationDate:
            - DateTime: ~
        product:
            - NotNull: ~
        client:
            - NotNull: ~

App\Entity\Product:
    properties:
        brand:
            - NotBlank: ~
        name:
            - NotBlank: ~
        description:
            - NotBlank: ~
        price:
            - NotBlank: ~
        weight:
            - NotBlank: ~
        width:
            - NotBlank: ~
        height:
            - NotBlank: ~
        screen:
            - NotBlank: ~
